AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Template to create an EC2 instance

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02xxxxx
      InstanceType: t2.micro
